'use strict';
// merge-review: collect each reviewer's JSON block into review-report.md and a verdict
// (spec §9 step 9, §10.3).

const fs = require('fs');
const path = require('path');
const S = require('./state');
const W = require('./workflow');

const SEV_ORDER = { critical: 0, major: 1, minor: 2, info: 3 };
const KNOWN_SEVERITIES = Object.keys(SEV_ORDER);

function readReviewer(folder, name) {
  const f = path.join(folder, 'review', `${name}.md`);
  if (!fs.existsSync(f)) return { name, present: false, findings: [], verdict: null, error: 'no report' };
  const text = fs.readFileSync(f, 'utf8');
  const block = text.match(/```json\s*([\s\S]*?)```/);
  if (!block) return { name, present: true, findings: [], verdict: null, error: 'no JSON block' };
  try {
    const data = JSON.parse(block[1]);
    return { name, present: true, findings: data.findings || [], verdict: data.verdict || null, error: null };
  } catch (e) {
    return { name, present: true, findings: [], verdict: null, error: `JSON block does not parse: ${e.message}` };
  }
}

function merge(root, id) {
  const state = S.readState(root, id);
  if (!state) throw new Error(`unknown work item: ${id}`);
  const cfg = S.loadConfig(root);
  const wf = W.load(root, state.type);
  const ph = W.getPhase(wf, 'review');
  if (!ph) throw new Error(`${state.type} has no review phase`);

  const folder = S.workFolder(root, state);
  const reviewers = cfg.review.reviewers;
  const blocking = ph.blocking_reviewers === 'all' || !ph.blocking_reviewers
    ? reviewers.slice()
    : ph.blocking_reviewers;
  const blockOn = new Set(cfg.review.block_on || ['critical', 'major']);

  const reports = reviewers.map((r) => readReviewer(folder, r));
  const findings = [];
  for (const rep of reports) {
    for (const f of rep.findings) {
      // A severity outside conventions.md §4 cannot be judged, so it fails closed.
      const unknown = !KNOWN_SEVERITIES.includes(f.severity);
      findings.push({
        ...f,
        reviewer: f.reviewer || rep.name,
        blocking: blocking.includes(rep.name) && (blockOn.has(f.severity) || unknown),
        unknown_severity: unknown || undefined,
      });
    }
  }
  findings.sort((a, b) => (SEV_ORDER[a.severity] ?? 9) - (SEV_ORDER[b.severity] ?? 9));

  const missing = reports.filter((r) => !r.present || r.error);
  const blockingFindings = findings.filter((f) => f.blocking);
  const verdict = blockingFindings.length || missing.length ? 'fail' : 'pass';

  const rel = S.relWorkFolder(root, state);
  const out = renderReport(state, { reports, findings, blockingFindings, missing, verdict, blocking, blockOn: [...blockOn] });
  fs.writeFileSync(path.join(folder, 'review-report.md'), out);

  return {
    verdict,
    id,
    report: `${rel}/review-report.md`,
    reviewers: reports.map((r) => ({ name: r.name, present: r.present, error: r.error, findings: r.findings.length })),
    findings,
    blocking: blockingFindings,
    fix_tasks: blockingFindings.map((f) => ({ task: `FIX-${f.id}`, finding: f.id, file: f.file, line: f.line, rule: f.rule, issue: f.issue })),
  };
}

function renderReport(state, d) {
  const row = (f) => `| ${f.id || ''} | ${f.reviewer} | ${f.severity} | ${f.file || ''}${f.line !== undefined ? ':' + f.line : ''} | ${f.rule || ''} | ${(f.issue || '').replace(/\|/g, '\\|')} | ${(f.fix || '').replace(/\|/g, '\\|')} |`;
  const blockingRows = d.findings.filter((f) => f.blocking);
  const advisory = d.findings.filter((f) => !f.blocking);
  return [
    '---',
    `id: ${state.id}`,
    'artifact: review-report',
    'version: 1',
    `status: final`,
    `refs: [${d.reports.filter((r) => r.present).map((r) => `review/${r.name}.md`).join(', ')}]`,
    '---',
    '',
    `# Review Report — ${state.title}`,
    '',
    '## Summary',
    `Generated by \`jarvis.js merge-review\`. Reviewers run: ${d.reports.map((r) => `${r.name}${r.present ? '' : ' (missing)'}`).join(', ')}.`,
    `Findings: ${d.findings.length} total, ${blockingRows.length} blocking.`,
    '',
    '## Verdict',
    `**${d.verdict}** — blocking reviewers: ${d.blocking.join(', ')}; blocking severities: ${d.blockOn.join(', ')}.`,
    d.missing.length ? `Missing or unparseable reports: ${d.missing.map((m) => `${m.name} (${m.error})`).join(', ')}.` : 'All enabled reviewers produced a parseable report.',
    '',
    '## Findings',
    '| ID | reviewer | severity | file:line | rule | issue | fix |',
    '|---|---|---|---|---|---|---|',
    ...(blockingRows.length ? blockingRows.map(row) : ['| none | | | | | | |']),
    '',
    '## Advisory',
    '| ID | reviewer | severity | file:line | rule | issue | fix |',
    '|---|---|---|---|---|---|---|',
    ...(advisory.length ? advisory.map(row) : ['| none | | | | | | |']),
    '',
  ].join('\n');
}

module.exports = { merge, readReviewer, renderReport };
